# Generated by Django 4.2 on 2024-07-29 14:26

import apps.home.custom_storage
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0002_unit_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('manager', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_projects', to=settings.AUTH_USER_MODEL)),
                ('team_members', models.ManyToManyField(related_name='projects', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='document',
            name='unit',
        ),
        migrations.RemoveField(
            model_name='document',
            name='uploaded_at',
        ),
        migrations.AddField(
            model_name='document',
            name='version',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='attachment',
            name='file',
            field=models.FileField(storage=apps.home.custom_storage.StaticFileSystemStorage(), upload_to='attachments/'),
        ),
        migrations.AlterField(
            model_name='document',
            name='file',
            field=models.FileField(storage=apps.home.custom_storage.StaticFileSystemStorage(), upload_to='documents/'),
        ),
        migrations.AlterField(
            model_name='maintenancehistory',
            name='document',
            field=models.FileField(blank=True, null=True, storage=apps.home.custom_storage.StaticFileSystemStorage(), upload_to='maintenance_documents/'),
        ),
        migrations.AlterField(
            model_name='openrepair',
            name='image',
            field=models.ImageField(blank=True, null=True, storage=apps.home.custom_storage.StaticFileSystemStorage(), upload_to='repair_images/'),
        ),
        migrations.AlterField(
            model_name='property',
            name='image_or_video',
            field=models.FileField(blank=True, null=True, storage=apps.home.custom_storage.StaticFileSystemStorage(), upload_to='property_media/'),
        ),
        migrations.AlterField(
            model_name='propertyinfo',
            name='legal_files',
            field=models.FileField(blank=True, null=True, storage=apps.home.custom_storage.StaticFileSystemStorage(), upload_to='legal_files/'),
        ),
        migrations.AlterField(
            model_name='tool',
            name='image',
            field=models.ImageField(blank=True, null=True, storage=apps.home.custom_storage.StaticFileSystemStorage(), upload_to='tools_images/'),
        ),
        migrations.AlterField(
            model_name='tool',
            name='location_image',
            field=models.ImageField(blank=True, null=True, storage=apps.home.custom_storage.StaticFileSystemStorage(), upload_to='tools_images/'),
        ),
        migrations.AlterField(
            model_name='unit',
            name='image_or_video',
            field=models.FileField(blank=True, null=True, storage=apps.home.custom_storage.StaticFileSystemStorage(), upload_to='unit_media/'),
        ),
        migrations.AlterField(
            model_name='unit',
            name='lease_agreement',
            field=models.FileField(blank=True, null=True, storage=apps.home.custom_storage.StaticFileSystemStorage(), upload_to='unit_media/'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='image',
            field=models.ImageField(blank=True, null=True, storage=apps.home.custom_storage.StaticFileSystemStorage(), upload_to='vehicle_images/'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='media',
            field=models.FileField(blank=True, null=True, storage=apps.home.custom_storage.StaticFileSystemStorage(), upload_to='vehicle_media/'),
        ),
        migrations.AlterField(
            model_name='vehicleimage',
            name='image',
            field=models.ImageField(storage=apps.home.custom_storage.StaticFileSystemStorage(), upload_to='vehicle_gallery/'),
        ),
        migrations.CreateModel(
            name='ReferenceMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=50)),
                ('content', models.TextField()),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='references', to='home.project')),
            ],
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='home.project')),
            ],
        ),
        migrations.AddField(
            model_name='document',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='home.project'),
        ),
        migrations.AddField(
            model_name='task',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='home.project'),
        ),
    ]
