# Generated by Django 4.2 on 2024-08-15 13:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_task_completed'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('0', 'Finish to Start (default)'), ('1', 'Start to Start'), ('2', 'Finish to Finish'), ('3', 'Start to Finish')], default='0', max_length=1)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='link_sources', to='home.task')),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='link_targets', to='home.task')),
            ],
        ),
    ]
