# Generated by Django 3.2.6 on 2024-07-30 22:42

import apps.home.custom_storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_projectdocument_is_model_alter_note_project_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectdocument',
            name='file',
            field=models.FileField(storage=apps.home.custom_storage.StaticFileSystemStorage(), upload_to='documents/'),
        ),
    ]
