# Generated by Django 4.2 on 2024-07-24 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_maintenancerecord_id_alter_tool_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tool',
            name='image',
            field=models.ImageField(upload_to='media/tools_images/'),
        ),
    ]
