# Generated by Django 3.2.6 on 2024-08-01 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20240730_2042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='referencematerial',
            name='type',
            field=models.CharField(choices=[('video', 'Video'), ('schematic', 'Schematic'), ('note', 'Note'), ('image', 'Image'), ('model', '3D Model')], max_length=50),
        ),
    ]
