# Generated by Django 4.2 on 2024-07-29 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_gameproject_financialreport_expense_budget'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='project_type',
            field=models.CharField(choices=[('construction', 'Construction'), ('game', 'Game')], default='construction', max_length=20),
        ),
    ]
