# Generated by Django 4.2 on 2024-07-25 12:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_vehicle_alter_tool_image_vehicleimage_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='maintenancerecord',
            name='tool',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_logs', to='home.tool'),
        ),
        migrations.AddField(
            model_name='tool',
            name='tags',
            field=models.ManyToManyField(blank=True, to='home.tag'),
        ),
    ]
