# Generated by Django 4.2 on 2024-09-24 15:37

import apps.home.custom_storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_materialcategory_project_allotted_budget_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectattachment',
            name='file',
            field=models.FileField(storage=apps.home.custom_storage.StaticFileSystemStorage(), upload_to='project_attachments/'),
        ),
        migrations.AlterField(
            model_name='projectimage',
            name='image',
            field=models.ImageField(storage=apps.home.custom_storage.StaticFileSystemStorage(), upload_to='project_images/'),
        ),
    ]
