# Generated by Django 4.2 on 2024-09-30 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_alter_projectattachment_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='cost_per_item',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='cost_per_square_foot',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='item_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='number_of_items',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
