# Generated by Django 4.2 on 2024-07-25 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_task_category_task_hours'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='vehicle_videos/'),
        ),
    ]
