# Generated by Django 4.2 on 2024-10-08 14:58

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_alter_invoice_valid_until'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='valid_until',
            field=models.DateField(default=datetime.datetime(2024, 12, 7, 14, 58, 38, 648406)),
        ),
        migrations.CreateModel(
            name='Panorama',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='tour_images/')),
                ('name', models.CharField(help_text="Name of the panorama (e.g., 'Living Room')", max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('initial_view_parameters', models.JSONField(blank=True, help_text='JSON configuration for initial pitch, yaw, etc.', null=True)),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='panoramas', to='home.unit')),
            ],
        ),
    ]
