# Generated by Django 4.2 on 2024-10-08 15:52

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_alter_invoice_valid_until_panorama'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='valid_until',
            field=models.DateField(default=datetime.datetime(2024, 12, 7, 15, 52, 51, 902923)),
        ),
        migrations.AlterField(
            model_name='panorama',
            name='initial_view_parameters',
            field=models.JSONField(blank=True, help_text='JSON configuration for initial pitch and yaw', null=True),
        ),
        migrations.CreateModel(
            name='Hotspot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pitch', models.FloatField(help_text='Vertical angle in degrees')),
                ('yaw', models.FloatField(help_text='Horizontal angle in degrees')),
                ('text', models.CharField(help_text='Text to display on hover', max_length=100)),
                ('panorama', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hotspots', to='home.panorama')),
                ('target_panorama', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_hotspots', to='home.panorama')),
            ],
        ),
    ]
