# Generated by Django 4.2 on 2024-10-15 12:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_alter_invoice_valid_until'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='valid_until',
            field=models.DateField(default=datetime.datetime(2024, 12, 14, 12, 45, 18, 898532)),
        ),
    ]
