# Generated by Django 4.2 on 2024-10-16 14:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0019_product_alter_invoice_valid_until_optiongroup_option_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='valid_until',
            field=models.DateField(default=datetime.datetime(2024, 12, 15, 14, 54, 16, 411620)),
        ),
    ]
