# Generated by Django 4.2 on 2024-10-17 08:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0021_cartitem_session_key_alter_invoice_valid_until'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='valid_until',
            field=models.DateField(default=datetime.datetime(2024, 12, 16, 8, 33, 15, 477993)),
        ),
    ]
