# Generated by Django 4.2 on 2024-07-25 13:05

import apps.home.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_tag_alter_maintenancerecord_tool_tool_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='tool',
            name='location_image',
            field=models.ImageField(blank=True, null=True, upload_to=apps.home.models.get_static_image_path),
        ),
        migrations.AddField(
            model_name='tool',
            name='location_x',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tool',
            name='location_y',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
