# Generated by Django 4.2 on 2024-07-25 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_vehicle_video'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicle',
            name='video',
        ),
        migrations.AddField(
            model_name='vehicle',
            name='media',
            field=models.FileField(blank=True, null=True, upload_to='vehicle_media/'),
        ),
    ]
