# Generated by Django 4.2 on 2024-07-25 19:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_remove_vehicle_video_vehicle_media'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='unit_documents/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='maintenancelog',
            name='unit',
        ),
        migrations.RemoveField(
            model_name='unitimage',
            name='unit',
        ),
        migrations.RemoveField(
            model_name='maintenancerecord',
            name='tool',
        ),
        migrations.RemoveField(
            model_name='property',
            name='number_of_floors',
        ),
        migrations.RemoveField(
            model_name='unit',
            name='floor',
        ),
        migrations.RemoveField(
            model_name='unit',
            name='image',
        ),
        migrations.AddField(
            model_name='maintenancerecord',
            name='unit',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_records', to='home.unit'),
        ),
        migrations.AddField(
            model_name='property',
            name='image_or_video',
            field=models.FileField(blank=True, null=True, upload_to='property_media/'),
        ),
        migrations.AddField(
            model_name='property',
            name='manager_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='unit',
            name='image_or_video',
            field=models.FileField(blank=True, null=True, upload_to='unit_media/'),
        ),
        migrations.AddField(
            model_name='unit',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='unit',
            name='property',
            field=models.ForeignKey(default=1010, on_delete=django.db.models.deletion.CASCADE, related_name='units', to='home.property'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Floor',
        ),
        migrations.DeleteModel(
            name='MaintenanceLog',
        ),
        migrations.DeleteModel(
            name='UnitImage',
        ),
        migrations.AddField(
            model_name='document',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='home.unit'),
        ),
    ]
