name: Azure Static Web Apps CI/CD

   on:
     push:
       branches:
         - main  # Set the branch you want to deploy from

   jobs:
     build_and_deploy_job:
       runs-on: ubuntu-latest
       name: Build and Deploy Job
       steps:
         - uses: actions/checkout@v2

         # Setup Python environment
         - name: Set up Python
           uses: actions/setup-python@v2
           with:
             python-version: '3.9'  # Specify the Python version you are using

         # Install dependencies
         - name: Install dependencies
           run: |
             python -m venv env
             source env/bin/activate
             pip install -r requirements.txt

         # Run Django collectstatic if needed
         - name: Collect static files
           run: |
             source env/bin/activate
             python manage.py collectstatic --noinput

         # Build and deploy the static web app
         - name: Build And Deploy
           id: builddeploy
           uses: Azure/static-web-apps-deploy@v1
           with:
             azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
             repo_token: ${{ secrets.GITHUB_TOKEN }}
             action: 'upload'
             app_location: '/'  # Location of your application source code
             api_location: 'api'  # Location of your API source code, if any
             output_location: 'build'  # Location of the built static files
             app_build_command: 'npm run build'  # Customize this command if needed