name: Django Static Web App CI/CD

    on:
      push:
        branches: [ master ]
      pull_request:
        branches: [ master ]

    jobs:
      build_and_deploy:
        runs-on: ubuntu-latest

        steps:
        - uses: actions/checkout@v2
        
        - name: Set up Python 3.8
          uses: actions/setup-python@v2
          with:
            python-version: 3.8

        - name: Install dependencies
          run: |
            python -m pip install --upgrade pip
            pip install -r requirements.txt

        - name: Collect static files
          run: |
            python manage.py collectstatic --noinput

        - name: Build and Deploy
          uses: Azure/static-web-apps-deploy@v1
          with:
            azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
            repo_token: ${{ secrets.GITHUB_TOKEN }} # Used for GitHub integrations (i.e. PR comments)
            action: "upload"
            app_location: "/" # Root of your repository
            output_location: "staticfiles" # Directory where static files are collected