name: Build & deploy container (Django + Dolibarr side-car)

on:
  push:
    branches: [ master ]          # adjust if you deploy from a different branch
  workflow_dispatch:

env:
  IMAGE_NAME:  ${{ github.repository_owner }}/hf-django   # <-- your Docker-Hub repo
  WEBAPP_NAME: HumanFutures                               # <-- Azure Web App name

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    # 1. Grab the code
    - uses: actions/checkout@v4

    # 2. Login to Docker Hub (needs two repo secrets)
    - name: Docker Hub login
      run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | \
           docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

    # 3. Build and push the image
    - name: Build & push image
      run: |
        docker build -t $IMAGE_NAME:latest .
        docker push  $IMAGE_NAME:latest

    # 4. Log in to Azure (OIDC or publish-profile — keep whichever you already use)
    - name: Azure login
      uses: azure/login@v2
      with:
        client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_B9833D2506694C1B9FD17D066ADBFB80 }}
        tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_8288A19A52C44135A788B0103D4DB614 }}
        subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_6C0B67B54A844958B48CBD9A7E241BBA }}

    # 5. Tell the Web App to pull the new tag
    - name: Deploy to Web App
      uses: azure/webapps-deploy@v3
      with:
        app-name:   $WEBAPP_NAME
        images:     docker.io/${{ env.IMAGE_NAME }}:latest
        slot-name:  production
