name: Build & deploy container

on:
  push:
    branches: [ master ]
  workflow_dispatch:

permissions:            # ← add this at the top (workflow-level)
  contents: read         #  ⬅️ allow checkout i

env:
  IMAGE_NAME:  michaelgrabinki/hf-django
  WEBAPP_NAME: HumanFutures

jobs:
  deploy:
    runs-on: ubuntu-latest

    # (all the existing steps stay the same)

    env:
      DOCKERHUB_USERNAME: michaelgrabinki  # Replace with your actual Docker Hub username
    steps:
    - uses: actions/checkout@v4

    # 1️⃣ Enable Docker
    - uses: docker/setup-buildx-action@v3

    # 2️⃣ Login to Docker Hub
    - uses: docker/login-action@v3
      with:
        username: ${{ env.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}  # Use a secret for the token

    # 3️ Build & push image
    - uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        tags: ${{ env.IMAGE_NAME }}:latest
        build-args: |
            BUILDKIT_PROGRESS=plain        # <-- temp flag
    
 # 4) Build & push the image
    - uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        tags: ${{ env.IMAGE_NAME }}:latest

    # 5) Deploy to Azure Web App (publish-profile)
    - uses: azure/webapps-deploy@v3
      with:
        app-name:        ${{ env.WEBAPP_NAME }}
        slot-name:       Production          # omit or change if you use slots
        publish-profile: ${{ secrets.AZURE_PUBLISH_PROFILE }}
        images:          docker.io/${{ env.IMAGE_NAME }}:latest